### ISSUE TITLE
Facebook Chat is replying automatically and it never stops!

### ISSUE THREAD

**Issue by ghost** [jaxl/JAXL#41]
Well i'm stuck in a really weird thing:
I've runned the basic example for connecting to the facebook chat but unfortunally i did not delete the event handler that replies to the "on_chat_message".
So basically now, everyone who messages me gets a reply n times the times i've reloaded the script.

It seems like there are n ghost active process on the facebook chat assigned to my user and I DON'T KNOW HOW TO KILL THEM :)

Please anyone knows what's going on?

**Comment by pmuralikrishna111** [comment]
FB Chat is now deprecated. You can close this thread.

Ref: https://developers.facebook.com/docs/chat

**Comment by frost-nzcr4** [comment]
Ok, thanks!
