### ISSUE TITLE
JAXL undefined variable client running with jaxlctl debug sock_file_name

### ISSUE THREAD

**Issue by ghoulich** [jaxl/JAXL#50]
I am trying to start a JAXL daemon by running JAXL's echo_bot.php.

It's working as I expected. The sock file is generated under .jaxl/sock/.

Then I use jaxl attach the sock file which I got from running echo_bot.php. I tried to run the example given here. But I get below error message when trying jaxlctl debug. It complains undefined variable, client Could you point me where I am wrong? Thanks!

$ ./jaxlctl debug .jaxl/sock/jaxl_3961
jaxl_socket_client:95 - 2014-04-30 10:39:55 - trying unix://.jaxl/sock/jaxl_3961
jaxl 2> global $client;
jaxl 3> $client->send_chat_msg('myaccount@xmpp.server.com', 'Hello JAXL');
jaxl_socket_client:175 - 2014-04-30 10:40:43 - socket eof, disconnecting

jaxl 1> jaxl_exception:48 - 2014-04-30 10:40:43 - got jaxl exception construct with Undefined variable: client, 8, /to_my_path/JAXL-3.x/jaxl.php(458) : eval()'d code, 1

**Comment by frost-nzcr4** [comment]
Duplicates #46
