### ISSUE TITLE
Fix the issue for latest PHP versions

### ISSUE THREAD

**Issue by turalsprofile** [jaxl/JAXL#60]
Please fix issue with latest PHP versions. Issue is exactly as in question below:

http://stackoverflow.com/questions/26654397/openfire-http-prebinding-with-jaxl/26795193#26795193

File is:

https://github.com/jaxl/JAXL/blob/v3.x/xep/xep_0206.php#L135

**Comment by abhinavsingh** [comment]
Thanks Tarul,

I think this has been known with JAXL for some time now (as new PHP
versions came out breaking backward compatibility). I also think there is a
similar PR that addresses it. I never got to merge it coz I no longer work
with PHP, XMPP or JAXL myself.

Can u draft a PR which can take care of it across various PHP versions?

**Comment by turalsprofile** [comment]
@abhinavsingh  what do you mean by PR?

**Comment by abhinavsingh** [comment]
Hi Tural,

I meant Pull Request (PR).
I remember this PR https://github.com/jaxl/JAXL/pull/36/files from @yang
It tries to address same issues that you faced.

------------------------------------------------------
Abhinav Singh,
http://abhinavsingh.com
------------------------------------------------------

**Comment by turalsprofile** [comment]
Honestly, I don't know if it fixes issue or not. I'm installing JAXL using composer. Not pulling via git. That's why I don't know. What I need is very simple task, I want to prebind using backend and transfer JID, RID to frontend. I need only this thing from whole XMPP. Can you help me on it?

**Comment by frost-nzcr4** [comment]
Should be fixed now. See #36
