### ISSUE TITLE
Develop Method for register user

### ISSUE THREAD

**Issue by bhavikdesai94** [jaxl/JAXL#72]
Hey, Can you create a new method in your library so by simply passing username and password anyone can register to ejjaberd server because i am facing problem to create method for register user so can u do this?

**Comment by abhinavsingh** [comment]
Please see [XEP-0077](https://github.com/jaxl/JAXL/blob/v3.x/xep/xep_0077.php) and it's usage

**Comment by bhavikdesai94** [comment]
I have seen XEP-0077 but how can i implement in my project i don't understood it.
You have use this file in your example register_user, but you are taking two array args and argv so from where both the array came i don't get it. In your example how can i pass username and password for new user registration.
that's why i said that can you make a simple method in jaxl.php file like register_user and it has parameters for username and password so it will create user, you made method send_chat_msg similar way can't you create register_user method because your current method is little bit complex for that person who doesn't familiar about the xmpp so if you do this type of method than anyone can easily understood your library.

**Comment by bhavikdesai94** [comment]
I tested your register_user.php file in terminal and its works successfully so now i want to use it using broswer so which type of changes i need to do in that file.
