### ISSUE TITLE
parsing JAXLxml

### ISSUE THREAD

**Issue by shivam21** [jaxl/JAXL#75]
I am making an chat app using firebase cloud messaging and easily obtained the response from xmpp server but don't know how to parse JAXLxml stanza in php. plz help

**Comment by frost-nzcr4** [comment]
Check this http://xmpp.org/extensions/xep-0124.html

**Comment by frost-nzcr4** [comment]
XMPPStanza is a wrapper for JAXLXml to get quick access to some properties, look at test https://github.com/jaxl/JAXL/blob/master/tests/test_xmpp_stanza.php#L71 and https://github.com/jaxl/JAXL/blob/master/xmpp/xmpp_stanza.php#L79
