### ISSUE TITLE
Why is there a hardcoded prefix for the resource?

### ISSUE THREAD

**Issue by sn0opy** [jaxl/JAXL#76]
https://github.com/jaxl/JAXL/blob/master/src/JAXL/jaxl.php#L242

Why is this hardcoded? I mean, I kinda understand to get credited for your work in some way, but if I set a resource, why do you still prepend `jaxl#` to it?

I'm totally okay, if it's prepended to the random generated resource though.

**Comment by frost-nzcr4** [comment]
Looks like some branding here and there or just testing stuff, because it's here from first implementation of resource f8bb72e547f8327e990f8b92a559aeafe6d1aa81

**Comment by sn0opy** [comment]
Okay, thanks for the reply. Probably going to create a PR for a few things here and there.
